#服务启动端口
server :  
  port :  8080

#数据库配置
spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:9966/study?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&autoReconnect=true&useSSL=false&verifyServerCertificate=false
        username: your.account
        password: your.pass
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
    redis:
      host: 127.0.0.1
      #redis密码，没有密码的可以用～表示
      password: ~
      port: 6379
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 100000
# Mybatis mapper 映射路径配置
mybatis:
  type-aliases-package: com.xiaour.spring.boot.mapper
  mapper-locations: classpath*:mapper/*.xml
  configLocation: classpath:mybatis-config.xml
    
# 日志输出
logging: 
    file: D:/boot.log
    level: 
        com.ibatis:DEBUG
        root:DEBUG

task:
    cron:0 0/5 * * * ?
       
    
